apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${YOUR_APP_NAME}-PV  # (important) este nombre del PV deber치 de coincidir con el PVC m치s adelante
spec:
  capacity:
    storage: ${STORAGE_SIZE_PV} # 1Gi  # size
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    # path: ./../assets/ # no recomendado utilizar paths relativos por la incompatibilidad con distintos tipos de cluster, adem치s de q kubernetes no permite ".."
    path: /opt/volumes/${YOUR_APP_NAME}/   # YOUR-PATH-PV  # ubicaci칩n en el nodo master del cluster