apiVersion: v1
kind: Service
metadata:
  name: ${YOUR_APP_NAME}-service
spec:
  type: NodePort
  selector:
    app: ${YOUR_APP_NAME} #Las etiquetas de selector que coinciden con las del Deployment para indicar qué Pods deben exponerse a través del servicio.
  ports:
    ${YOUR_SERVICE_PORTS}